[package]
name = "standalone-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.27.0", features = ["events", "use-dev-tty"] }
ratatui = { version = "0.27.0", features = ["unstable-widget-ref"] }
anyhow = "1.0.86"
crossbeam = "0.8.4"
chrono = "0.4.38"
