---
name: Pull Request Workflow
# yamllint disable-line rule:truthy
on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-spdx-headers:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Get files for PR
        # yamllint disable-line rule:line-length
        uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32 # v46.0.1
        id: changed-files
        with:
          separator: "," # Space-separated output
      - name: Verify SPDX headers
        # yamllint disable-line rule:line-length
        uses: rucoder/spdx@fbe91fbffc0ae3f55ae6f2b9ab0adb41a4083ad0 # v1
        with:
          licenses: |-
            Apache-2.0
          files: ${{ steps.changed-files.outputs.all_changed_files }}
          copyright: "Zededa, Inc."
  build:
    runs-on: ubuntu-latest
    needs: check-spdx-headers

    steps:
      - name: checkout
        # yamllint disable-line rule:line-length
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
